### ISSUE TITLE
IOError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by fgeek** [Diaoul/enzyme#16]
Fuzzed sample: http://bugs.fi/media/afl/enzyme/enzyme-008.mkv
Fuzzers used: http://lcamtuf.coredump.cx/afl/ https://bitbucket.org/jwilk/python-afl
SHA1: f5150df5239856849977e711945631a31f325f48
Notes: This is similar to issue #10

mkvinfo.py:
```
import sys
import enzyme
inputfile = sys.argv[1]
try:
    with open(inputfile, 'rb') as f:
        mkv = enzyme.MKV(f)
    print(mkv.info)
    print(mkv.video_tracks)
    print(mkv.audio_tracks)
except enzyme.exceptions.MalformedMKVError:
    pass
```
```
Traceback (most recent call last):
  File "mkvinfo.py", line 8, in <module>
    mkv = enzyme.MKV(f)
  File "/usr/local/lib/python2.7/dist-packages/enzyme-0.4.1-py2.7.egg/enzyme/mkv.py", line 40, in __init__
    segments = ebml.parse(stream, specs, ignore_element_names=['EBML'], max_level=0)
  File "/usr/local/lib/python2.7/dist-packages/enzyme-0.4.1-py2.7.egg/enzyme/parsers/ebml/core.py", line 172, in parse
    stream.seek(element.size, 1)
IOError: [Errno 22] Invalid argument
```

**Comment by fgeek** [comment]
Very similar issue..

Fuzzed sample: http://bugs.fi/media/afl/enzyme/enzyme-009.mkv
Fuzzers used: http://lcamtuf.coredump.cx/afl/ https://bitbucket.org/jwilk/python-afl
SHA1: af1f6d3b031c3f22a95cbdb473bf7882cb1e6858

mkvinfo.py:
```
import sys
import enzyme
inputfile = sys.argv[1]
try:
    with open(inputfile, 'rb') as f:
        mkv = enzyme.MKV(f)
    print(mkv.info)
    print(mkv.video_tracks)
    print(mkv.audio_tracks)
except enzyme.exceptions.MalformedMKVError:
    pass
```
```
Traceback (most recent call last):
  File "mkvinfo.py", line 8, in <module>
    mkv = enzyme.MKV(f)
  File "/usr/local/lib/python2.7/dist-packages/enzyme-0.4.1-py2.7.egg/enzyme/mkv.py", line 40, in __init__
    segments = ebml.parse(stream, specs, ignore_element_names=['EBML'], max_level=0)
  File "/usr/local/lib/python2.7/dist-packages/enzyme-0.4.1-py2.7.egg/enzyme/parsers/ebml/core.py", line 177, in parse
    stream.seek(element.size, 1)
IOError: [Errno 22] Invalid argument
```
