### ISSUE TITLE
Question about enzyme.exceptions.MalformedMKVError: Parsing error: Cannot read element id

### ISSUE THREAD

**Issue by fernandog** [Diaoul/enzyme#23]
@Diaoul 
when I run this I get that error but i don't get any error running `mkvinfo` in linux:

What Im missing?

``` python
>>> import enzyme
>>> with open('/media/SAMSUNG/media/series/1.mkv', 'rb') as f:
...     mkv = enzyme.MKV(f)
...     mkv.info
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/enzyme/mkv.py", line 56, in __init__
    raise MalformedMKVError('Parsing error: %s' % e)
enzyme.exceptions.MalformedMKVError: Parsing error: Cannot read element id
>>>

```

but when i run MKVINFO it shows no error:

```
mkvinfo "/media/SAMSUNG/media/series/1.mkv"
|+ Doc type: matroska
|+ Doc type version: 4
|+ Doc type read version: 2
+ Segment, size 1803643838
|+ Seek head (subentries will be skipped)
|+ EbmlVoid (size: 4027)
|+ Segment information
| + Timecode scale: 1000000
| + Muxing application: libebml v1.3.3 + libmatroska v1.4.4
| + Writing application: mkvmerge v9.1.0 ('Little Earthquakes') 64bit
| + Duration: 2582.956s (00:43:02.956)
| + Date: Tue May 10 05:13:51 2016 UTC
| + Segment UID: 0xb0 0x20 0xaa 0xa8 0xdc 0x7e 0x34 0xf7 0xa8 0x9b 0xaa 0xbc 0x7b 0x89 0x02 0xca
|+ Segment tracks
| + A track
|  + Track number: 1 (track ID for mkvmerge & mkvextract: 0)
|  + Track UID: 16362155880837181071
|  + Track type: video
|  + Lacing flag: 0
|  + MinCache: 1
|  + Codec ID: V_MPEG4/ISO/AVC
|  + CodecPrivate, length 43 (h.264 profile: High @L4.0)
|  + Default duration: 41.708ms (23.976 frames/fields per second for a video track)
|  + Video track
|   + Pixel width: 1920
|   + Pixel height: 1080
|   + Display width: 1920
|   + Display height: 1080
| + A track
|  + Track number: 2 (track ID for mkvmerge & mkvextract: 1)
|  + Track UID: 16338768801695860104
|  + Track type: audio
|  + Codec ID: A_AC3
|  + Default duration: 32.000ms (31.250 frames/fields per second for a video track)
|  + Audio track
|   + Sampling frequency: 48000
|   + Channels: 6
| + A track
|  + Track number: 3 (track ID for mkvmerge & mkvextract: 2)
|  + Track UID: 18344974354018286494
|  + Track type: subtitles
|  + Lacing flag: 0
|  + Codec ID: S_TEXT/UTF8
|+ EbmlVoid (size: 1147)
|+ Cluster
```

**Comment by morpheus65535** [comment]
@fernandog What was the resolution for this error?

I have a user with the same error in Bazarr:
https://github.com/morpheus65535/bazarr/issues/336
